// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwsWXMZbOxGUnvKgOSvnFPHGQFXi03N9M',
    appId: '1:976138766828:web:d62b7d2fd6335e0857d8c9',
    messagingSenderId: '976138766828',
    projectId: 'newsapp-1edef',
    authDomain: 'newsapp-1edef.firebaseapp.com',
    storageBucket: 'newsapp-1edef.firebasestorage.app',
    measurementId: 'G-BK0YD4856L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5C2w5sA-W7UsfWZ3jx41BL3Uz8NM4ho',
    appId: '1:976138766828:android:13b70fc5aa0e681657d8c9',
    messagingSenderId: '976138766828',
    projectId: 'newsapp-1edef',
    storageBucket: 'newsapp-1edef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzktpSa7ilvLfdpywNz2VRYTTUaHV27SU',
    appId: '1:976138766828:ios:2cf36439e805005757d8c9',
    messagingSenderId: '976138766828',
    projectId: 'newsapp-1edef',
    storageBucket: 'newsapp-1edef.firebasestorage.app',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzktpSa7ilvLfdpywNz2VRYTTUaHV27SU',
    appId: '1:976138766828:ios:2cf36439e805005757d8c9',
    messagingSenderId: '976138766828',
    projectId: 'newsapp-1edef',
    storageBucket: 'newsapp-1edef.firebasestorage.app',
    iosBundleId: 'com.example.news',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwsWXMZbOxGUnvKgOSvnFPHGQFXi03N9M',
    appId: '1:976138766828:web:091e54b94715234f57d8c9',
    messagingSenderId: '976138766828',
    projectId: 'newsapp-1edef',
    authDomain: 'newsapp-1edef.firebaseapp.com',
    storageBucket: 'newsapp-1edef.firebasestorage.app',
    measurementId: 'G-ECBH1D1QKM',
  );
}
